### ISSUE TITLE
 Create an ophy device for Andor2 detector on p99

### ISSUE THREAD

**Issue by Relm-Arrowny** [DiamondLightSource/dodal#381]
Create an ophy device for Andor2 detector (CCD) on p99

## Acceptance Criteria
- [ ]  Create an ophy device for Andor2
       1.  The detector should be stageable 
             Able to change Acquistion setting, exposure time trigger mode, eg things that need to be change during each data collection                     
       2.  Should be able to change Andor Diver setting, chip temperature readout time etc.
       3. Should be able to write data to somewhere.
       4. Ability to access arr of the image for data visualisation? 
       5. should be able to be use in bluesky plan.

### Tasks
- [ ]  Test what functionality of the detector has using epic PV, eg does the roi work etc etc.
- [ ]  Go through the device on i22 to draw up a proper task list. (see Ref #332) 
- [ ] Create the device
- Add extra functionality that needed in drivers,controller, plans like  [pimte]( https://github.com/Relm-Arrowny/i10-bluesky/issues/12)
- [ ] Device unit test
- [ ] IRL test

### Related Resources

https://github.com/Relm-Arrowny/p99Bluesky/issues/4
