### ISSUE TITLE
create CCD pimte area detector device

### ISSUE THREAD

**Issue by Relm-Arrowny** [DiamondLightSource/dodal#428]
Pimte is one of the few CCD detector used around diamond and it is useful to be able to use them in bluesaky , it could also serve as the base class for p99 CCD detector #381 

## Acceptance Criteria
- [x]  Create an ophyd-async  device for pimte
- [x]  1.  The detector should be stageable 
             Able to change Acquistion setting, exposure time trigger mode, eg things that need to be change during each data collection                     
- [x]  2.  Should be able to change Diver setting, chip temperature readout time etc.
- [x]  3. Should be able to write data to somewhere.
- [x]  5. should be able to be use in bluesky plan.

### Tasks
- [x]  Test what functionality of the detector has using epic PV, eg does the roi work etc etc.
- [x]  Go through the device on i22 to draw up a proper task list. (see Ref #332) 
- [x] Create the device
- Add extra functionality that needed in drivers like [pilatus_driver.py](https://github.com/bluesky/ophyd-async/blob/main/src/ophyd_async/epics/areadetector/drivers/pilatus_driver.py) 
- A controller much like [pilatus_controller.py](https://github.com/bluesky/ophyd-async/blob/main/src/ophyd_async/epics/areadetector/controllers/pilatus_controller.py) to deal with how the data collection is done setting trigger, count time etc....
- [x] Run it in bluesky
- [x] Device unit test
- Controller and drivers test is required. [example](https://github.com/bluesky/ophyd-async/tree/main/tests/epics/areadetector)  
- [x] IRL test
- Should be able to produce images with different exposure time, change all the setting that are required for the image itself.

##Ref
[i10 version ](https://github.com/Relm-Arrowny/i10-bluesky/issues/12)
